import csv
import re
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = BASE_DIR / "db_init.sql"


def sql_string(value):
    """Преобразовать текст в SQL-строку."""
    if value is None:
        return "NULL"
    value = str(value)
    value = value.replace("'", "''")
    return "'" + value + "'"


def extract_year(title):
    """Извлечь год из конца названия фильма."""
    match = re.search(r"\((\d{4})\)\s*$", title)
    if match:
        return int(match.group(1))
    return None


def read_movies():
    movies = []

    with open(BASE_DIR / "movies.csv", "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        for row in reader:
            movie_id = int(row["movieId"])
            title = row["title"]
            year = extract_year(title)
            genres = row["genres"]

            movies.append((movie_id, title, year, genres))

    return movies


def read_ratings():
    ratings = []

    with open(BASE_DIR / "ratings.csv", "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        for row_id, row in enumerate(reader, start=1):
            ratings.append(
                (
                    row_id,
                    int(row["userId"]),
                    int(row["movieId"]),
                    float(row["rating"]),
                    int(row["timestamp"]),
                )
            )

    return ratings


def read_tags():
    tags = []

    with open(BASE_DIR / "tags.csv", "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        for row_id, row in enumerate(reader, start=1):
            tags.append(
                (
                    row_id,
                    int(row["userId"]),
                    int(row["movieId"]),
                    row["tag"],
                    int(row["timestamp"]),
                )
            )

    return tags


def read_users():
    users = []

    with open(BASE_DIR / "users.txt", "r", encoding="utf-8-sig") as file:
        for line_number, line in enumerate(file, start=1):
            line = line.rstrip("\r\n")

            if not line:
                continue

            parts = line.split("|")

            if len(parts) != 6:
                raise ValueError(
                    f"Некорректная строка users.txt №{line_number}: "
                    f"ожидалось 6 полей, получено {len(parts)}"
                )

            user_id, name, email, gender, register_date, occupation = parts

            users.append(
                (
                    int(user_id),
                    name,
                    email,
                    gender,
                    register_date,
                    occupation,
                )
            )

    return users


def generate_sql():
    movies = read_movies()
    ratings = read_ratings()
    tags = read_tags()
    users = read_users()

    with open(OUTPUT_FILE, "w", encoding="utf-8", newline="\n") as sql:
        sql.write("-- Generated by make_db_init.py\n")
        sql.write("PRAGMA foreign_keys = OFF;\n")
        sql.write("BEGIN TRANSACTION;\n\n")

        sql.write("DROP TABLE IF EXISTS movies;\n")
        sql.write("DROP TABLE IF EXISTS ratings;\n")
        sql.write("DROP TABLE IF EXISTS tags;\n")
        sql.write("DROP TABLE IF EXISTS users;\n\n")

        sql.write(
            """CREATE TABLE movies (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    year INTEGER,
    genres TEXT
);

"""
        )

        sql.write(
            """CREATE TABLE ratings (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    movie_id INTEGER,
    rating REAL,
    timestamp INTEGER
);

"""
        )

        sql.write(
            """CREATE TABLE tags (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    movie_id INTEGER,
    tag TEXT,
    timestamp INTEGER
);

"""
        )

        sql.write(
            """CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name TEXT,
    email TEXT,
    gender TEXT,
    register_date TEXT,
    occupation TEXT
);

"""
        )

        for movie_id, title, year, genres in movies:
            year_value = "NULL" if year is None else str(year)

            sql.write(
                "INSERT INTO movies (id, title, year, genres) VALUES "
                f"({movie_id}, {sql_string(title)}, {year_value}, "
                f"{sql_string(genres)});\n"
            )

        sql.write("\n")

        for row_id, user_id, movie_id, rating, timestamp in ratings:
            sql.write(
                "INSERT INTO ratings "
                "(id, user_id, movie_id, rating, timestamp) VALUES "
                f"({row_id}, {user_id}, {movie_id}, {rating}, {timestamp});\n"
            )

        sql.write("\n")

        for row_id, user_id, movie_id, tag, timestamp in tags:
            sql.write(
                "INSERT INTO tags "
                "(id, user_id, movie_id, tag, timestamp) VALUES "
                f"({row_id}, {user_id}, {movie_id}, "
                f"{sql_string(tag)}, {timestamp});\n"
            )

        sql.write("\n")

        for user_id, name, email, gender, register_date, occupation in users:
            sql.write(
                "INSERT INTO users "
                "(id, name, email, gender, register_date, occupation) VALUES "
                f"({user_id}, {sql_string(name)}, {sql_string(email)}, "
                f"{sql_string(gender)}, {sql_string(register_date)}, "
                f"{sql_string(occupation)});\n"
            )

        sql.write("\nCOMMIT;\n")

    print(f"SQL script generated: {OUTPUT_FILE}")
    print(f"Movies:  {len(movies)}")
    print(f"Ratings: {len(ratings)}")
    print(f"Tags:    {len(tags)}")
    print(f"Users:   {len(users)}")


if __name__ == "__main__":
    generate_sql()
